const config = {
    API_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cm90aHVtYXRzeWpwY2tiZ3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzg3MjgyNDksImV4cCI6MTk5NDMwNDI0OX0.dVF59XvFesnIvalXRzCWxRMgsYiEoHEUshpB1TkgDbg'
};

export default config;